<?php

namespace AppBundle\Repository\Entity;

/**
 * findWithIngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class findWithIngredientsRepository extends \Doctrine\ORM\EntityRepository
{
}
