<?php

namespace AppBundle\Repository\Entity;

/**
 * findRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class findRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
