<?php

namespace AppBundle\Repository;

/**
 * recipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recipesRepository extends \Doctrine\ORM\EntityRepository
{
}
