<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository
{
    public function findRecipeWithIngredientsId($recipeToSearch)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM AppBundle:Recipe r WHERE r.name = :name')
            ->setParameter('name', $recipeToSearch)
            ->getResult();
    }
}
