<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository
{
    public function findRecipeWithIngredientsId($ingredientToSearch)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r.recipe_id FROM AppBundle:recipe_ingredient r WHERE r.ingredient_id = :ingredient_id')
            ->setParameter('ingredient_id', $ingredientToSearch)
            ->getResult();
    }
}
