homepage:
    path: /
    controller: AppBundle\Controller\DefaultController::indexAction

registration_user:
    path: /register
    controller: AppBundle\Controller\RegistrationController::registerAction

addIngredient:
  path: /addIngredient
  controller: AppBundle\Controller\IngredientController::addIngredientAction

#FOSUser Bundle routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile